# Generated by Django 4.0.4 on 2022-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.URLField(max_length=1500),
        ),
    ]
